### ISSUE TITLE
Column Specification Clarification

### ISSUE THREAD

**Issue by billdenney** [paolobrasolin/topiclongtable#1]
In the readme, you state the following:

> To give the column specification you will have to prepend `F` to the first one and `T` to subsequent ones.

For non-topic columns, is the `T` optional or not.  Specifically, would the following work since the last column is not a "topic" column (note the removed `T` for the last column relative to what is in the readme):

`\begin{topiclongtable}{|Fl|Tl|Tl|l|}`

**Comment by paolobrasolin** [comment]
That would work. Unexpected behaviour (erroneous line drawing) arises only when `\Topic` is used in unmarked columns. Adding the following clarification to the readme:

> The prefix can be safely omitted on columns after the last one containing `topiclongtable` macros.
