### ISSUE TITLE
TopicLine Only Crosses Last Column

### ISSUE THREAD

**Issue by billdenney** [paolobrasolin/topiclongtable#10]
I just created a document where the `\TopicLine` didn't extend as far as I thought it should.  Can you please help troubleshoot what I should do differently in the document or if a code fix is needed?

The issue is in the last row where the horizontal line should extend through the "desc", "est param", and "rse" columns, but it only crosses the "rse" column.

```tex
\documentclass[]{article}
\usepackage{siunitx}
\usepackage{topiclongtable}

\begin{document}

\begin{topiclongtable}{|Fr|Tr|Tr|Tr|Tr|Tl|l|r|r|}


\hline model & ofv & ref & rofv & dOFV & signif & desc & est param & rse \\
\hline
\endfirsthead
\multicolumn{9}{@{}l}{\ldots continued} \\
\hline model & ofv & ref & rofv & dOFV & signif & desc & est param & rse \\
\hline
\endhead
\hline
\multicolumn{9}{r@{}}{continued \ldots} \\
\endfoot
\hline
\endlastfoot
\TopicLine \Topic[ 1] & \Topic[3646.222] & \Topic[NA] & \Topic[      NA] & \Topic[    NA] & \Topic[-  ] & NA     &    NA &   NA \\
\TopicLine \Topic[ 2] & \Topic[3645.408] & \Topic[ 1] & \Topic[3646.222] & \Topic[ 0.814] & \Topic[No ] & 15 Foo &  0.03 & 1.40 \\
\TopicLine \Topic[ 3] & \Topic[3645.685] & \Topic[ 1] & \Topic[3646.222] & \Topic[ 0.537] & \Topic[No ] & 16 Foo & -0.06 & 1.40 \\
\TopicLine \Topic[ 4] & \Topic[3645.164] & \Topic[ 1] & \Topic[3646.222] & \Topic[ 1.058] & \Topic[No ] & 17 Foo &  0.14 & 0.94 \\
\TopicLine \Topic[ 5] & \Topic[3645.523] & \Topic[ 1] & \Topic[3646.222] & \Topic[ 0.699] & \Topic[No ] & 18 Foo &  0.60 & 1.60 \\
\TopicLine \Topic[ 6] & \Topic[3642.900] & \Topic[ 1] & \Topic[3646.222] & \Topic[ 3.322] & \Topic[No ] & 19 Foo & -0.30 & 0.93 \\
\TopicLine \Topic[ 7] & \Topic[3628.286] & \Topic[ 1] & \Topic[3646.222] & \Topic[17.936] & \Topic[Yes] & 20 Foo &  0.00 & 0.20 \\
\TopicLine \Topic[14] & \Topic[3624.156] & \Topic[ 7] & \Topic[3628.286] & \Topic[ 4.130] & \Topic[No ] & 19 Foo & -0.90 & 0.34 \\
\TopicLine \Topic[14] & \Topic[3624.156] & \Topic[ 7] & \Topic[3628.286] & \Topic[ 4.130] & \Topic[No ] & 20 Foo &  0.50 & 0.66 \\
\end{topiclongtable}

\end{document}
```

Result:
![image](https://user-images.githubusercontent.com/10359931/50569895-020db980-0d41-11e9-9675-ac89fcf3154e.png)

**Comment by paolobrasolin** [comment]
I confirm the bug exists.

A quick fix is *not omitting* the `T` column type on the rightmost columns:

```tex
\begin{topiclongtable}{|Fr|Tr|Tr|Tr|Tr|Tl|Tl|Tr|Tr|}
```

Perhaps the best course of action would be to remove the optionality from the documentation, since
* optionality of `T` on rightmost columns was more of a side effect than a deliberately implemented feature,
* it makes the interface slightly more complicated instead of simpler (allowing exceptions instead of enforcing a rule), and
* the convenience factor is relatively small.

What do you think @billdenney ?

**Comment by billdenney** [comment]
Inclusion or exclusion of the `T` isn't so important to me, either way.  I have a few questions to confirm the behavior and updates to the implementation:

* I'd like to confirm that `\Topic` defines what is or is not a topic regardless of `T` in the alignment header.  Specifically, I do not want all the columns to be handled like topic columns if the contents are not wrapped in `\Topic`.  (There could be columns that incidentally have the same value where I don't want them to be combined unless wrapped in `\Topic`.)
* If `T` is then assumed for all columns, instead of requiring it for all columns, can it be omitted from all (since it is assumed for all columns that are not the one marked with `F`)?  (If it's problematic, as you say, the inconvenience is small, so this isn't a major request.)
* And, if `T` is possible to be optional because it is always assumed, could `F` also be optional (because it can be detected as the first)?  I remember that we had a conversation about that during the initial design, but I don't recall the rationale, and as you maybe looking into some parts of the column specification, I thought I'd re-ask.

**Comment by paolobrasolin** [comment]
> Specifically, I do not want all the columns to be handled like topic columns if the contents are not wrapped in `\Topic`.

Only column cells wrapped in `\Topic` will combine. Other cells will have ordinary behaviour.

In fact, `F` and `T` do very simple things: `F` resets a column counter and `T` increases it.
Nothing else. They are pretty much trivial column styles: [here is the implementation](https://github.com/paolobrasolin/topiclongtable/blob/49daa825907acee53729ea38b1fcb47d96ed2a68/topiclongtable.sty#L383).

I chose this approach to avoid patching `table` or `topiclongtable` internals and give up some convenience to in favour of a more predictable and intelligible implementation.

Of course it's possible to do the same thing without requiring the use of extra column style markers, but I think the effort would be disproportionately higher.

**Comment by billdenney** [comment]
“Disproportionately higher” effort or patching internals is not the goal.  Let’s keep “F” and “T”.

Thanks for the explanation.

**Comment by billdenney** [comment]
Can you please update the documentation to indicate that `T` is required and then close this?

**Comment by paolobrasolin** [comment]
@billdenney Just made a PR. If that looks good to you I'll release to CTAN later today.

**Comment by billdenney** [comment]
Looks great!
